### ISSUE TITLE
Blockchain SSL support

### ISSUE THREAD

**Issue by ghost** [vbuterin/pybitcointools#10]
Hi
It seems that all calls to the Blockchain API are done via HTTP instead of HTTPS. This is problematic as it allows snooping parties to determine what addresses/transactions we're interested in and potentially own.
Regards,
Vedran

**Comment by zhs** [comment]
Same problem when I call history():

  File "./pybitcointools/bitcoin/bci.py", line 23, in make_request
    raise Exception(p)
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
