### ISSUE TITLE
Posible broken code in transaction.py

### ISSUE THREAD

**Issue by carlinhoxapo** [vbuterin/pybitcointools#118]
Hi,

We found a posible error in the syntax of transaction.py in line 141

        for out in newtx["outs'][:len(newtx["ins"]) - 1)]:

we added a ( before len and used double quotes to close outs

for out in newtx["outs"][:(len(newtx["ins"]) - 1)]:

Regards

Carlos

**Comment by reiven** [comment]
Yes @carlinhoxapo there is a PullRequest to fix it #117

**Comment by carlinhoxapo** [comment]
Did not see that one! Thanks!!

**Comment by reiven** [comment]
@carlinhoxapo as the PR was fixed, you can close this issue

**Comment by carlinhoxapo** [comment]
Great Thanks!
