### ISSUE TITLE
Pypi bitcoin package v1.1.40 is broken

### ISSUE THREAD

**Issue by RCL-Carl** [vbuterin/pybitcointools#138]
The [v1.1.40 package `bitcoin`](https://pypi.python.org/pypi/bitcoin) in the pypi repo lacks the file "bitcoin/english.txt" in the tar ball which causes the setup.py script to fail on install.

**Comment by yurivict** [comment]
+1

**Comment by maurycyp** [comment]
+1
This also break the `ethereum` library ( https://pypi.python.org/pypi/ethereum ) and everything that uses it, since the `bitcoin` version there is unpinned.

**Comment by vbuterin** [comment]
Sorry about that!

Should be fixed now.

**Comment by RCL-Carl** [comment]
A very quick test of pip used in virtualenv confirms that this has been fixed. 
Thanks!
