### ISSUE TITLE
Does get_pubkey_format need all the extra checks?

### ISSUE THREAD

**Issue by eleutheros** [vbuterin/pybitcointools#25]
In get_pubkey_format, you not only check the lengths of the pubkeys, but you also check substrings of the pubkeys. Do you need to do this? You don't do it in get_privkey_format. Also, it looks like the encode functions are correct, so why do you need to check in this function? These questions might not make much sense, but I'm trying to be clear about reasoning behind some parts of the code, because I am trying to translate it to Racket Scheme.

**Comment by vbuterin** [comment]
Yep, that's necessary. Pubkeys have more restrictive semantics in all standard formats.
