### ISSUE TITLE
2 diff addresses from the same HD prvkey

### ISSUE THREAD

**Issue by themighty1** [vbuterin/pybitcointools#57]
I created a privkey from my HD master key:
mk = bitcoin.bip32_master_key('seed')
prv = bitcoin.bip32_ckd(mk,0)

Which of the below should I use to get the address?

bitcoin.pubkey_to_address(bitcoin.bip32_privtopub(prv))
>>>'1PryoY2TVGno95zueXavej8xetFxxWmwXq'

bitcoin.privkey_to_address(bitcoin.encode_privkey(bitcoin.bip32_extract_key(prv), 'wif'))
>>>'1LbQvv9Xzxmm3RPVgCVhnmyfDR4Tke2GLB'

**Comment by vbuterin** [comment]
Ah!

You want bitcoin.privkey_to_address(bitcoin.encode_privkey(bitcoin.bip32_extract_key(prv), 'wif_compressed')) . You were using compressed privkeys, and 'wif' converted it to standard, ie. uncompressed form, which produces different addresses.
