### ISSUE TITLE
signining chokes on unicode strings

### ISSUE THREAD

**Issue by arnuschky** [vbuterin/pybitcointools#69]
Signing transactions represented using unicode strings (standard in python) fails in `signature_form`:

```python
def signature_form(tx, i, script, hashcode = SIGHASH_ALL):
    i, hashcode = int(i), int(hashcode)
    if isinstance(tx, str):
        return serialize(signature_form(deserialize(tx), i, script, hashcode))
    newtx = copy.deepcopy(tx)
```

Here, the check `if isinstance(tx, str):` fails. It should read `if isinstance(tx, str) or isinstance(tx, unicode):`.

User-side workaround: 
```python
signed_raw_tx = pybitcointools.signall(tx.encode('ascii','ignore'), privateKey)
```

**Comment by vbuterin** [comment]
Latest version already does if isinstance(tx, (str, unicode)) . Which
version are you using?

**Comment by arnuschky** [comment]
I used the one that installs when using pip. I also thought that I checked the code on github, but I must have been on an old branch while doing this. Sorry for the noise.
