### ISSUE TITLE
How to validate bip32 xpub keys and bitcoin addresses?

### ISSUE THREAD

**Issue by derrend** [vbuterin/pybitcointools#92]
I hope I'm in the right place, as the title suggests I'm looking for a way to check if a string is either a valid bip32 pub key or a valid btc address.

Having a hard time finding a python function that achieves this, is this possible with this library and if so please could you give me a hint ;)

Thank you

**Comment by derrend** [comment]
Not to worry, I got it working using `pycoin` from Richard Kiss.

**Comment by simcity4242** [comment]
Did you ask the same question on Bitcoin SE?

**Comment by derrend** [comment]
Yes and I did get an answer but I ended up using pycoin
https://bitcoin.stackexchange.com/questions/37310/how-can-i-check-if-a-bip32-xpub-key-is-valid-using-python/37313#37313
